name: Codex Generate & PyTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.11"
  CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  codex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --no-cache-dir --upgrade --force-reinstall codex-cli==1.0.1
          python -m pip show codex_cli

      - name: Add pip user bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Debug codex-cli install
        run: which codex-cli && codex-cli --help

      - name: Run Codex (CLI)
        run: codex-cli generate --ci

      - name: Run tests
        run: pytest -q
