name: Codex Generate & PyTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.11"
  CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  codex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          pip install openai langgraph codex-cli

      - name: Run Codex
        run: python -m codex generate --ci

      - name: Run tests
        run: pytest -q
