name: Codex Generate & PyTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.11"
  CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  codex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Verify Python Version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --no-cache-dir --upgrade --force-reinstall codex_cli==1.0.1

      - name: Debug Installation
        run: python -m pip show codex_cli

      - name: Verify codex_cli import
        run: python -c "import codex_cli.cli"

      - name: Run Codex
        run: python -m codex_cli.cli generate --ci

      - name: Run tests
        run: pytest -q
